dynamixel_loop:
  joint_state_controller:
    type: joint_state_controller/JointeStateController
    publish_rate: 50

  first_position_controoler:
    type: position_controllers/JointPositionController
    joint: first